CC=gcc

TARGET_NTGRBAK=NtgrBak
TARGETS=$(TARGET_NTGRBAK)
LIBS_NTGRBAK=-lcrypto
OBJS_NTGRBAK=\
src/NtgrBak.o

CFLAGS_DEFAULT=-Wall
CFLAGS_DEBUG=-g3
CFLAGS_RELEASE=-g0
LDFLAGS_DEFAULT=
LDFLAGS_DEBUG=
LDFLAGS_RELEASE=-s

ifdef DEBUG
CFLAGS=$(CFLAGS_DEFAULT) $(CFLAGS_DEBUG)
LDFLAGS=$(LDFLAGS_DEFAULT) $(LDFLAGS_DEBUG)
else
CFLAGS=$(CFLAGS_DEFAULT) $(CFLAGS_RELEASE)
LDFLAGS=$(LDFLAGS_DEFAULT) $(LDFLAGS_RELEASE)
endif


all: $(TARGETS)

$(TARGET_NTGRBAK): $(OBJS_NTGRBAK)
	$(CC) $(LDFLAGS) $(LIBS_NTGRBAK) -o $(TARGET_NTGRBAK) $(OBJS_NTGRBAK)

%.o: %.c %.h
	$(CC) -c $< $(CFLAGS) $(LIBS) -o $@

clean:
	rm -vf src/*.o
	rm -vf $(TARGETS)
