CC=gcc

TARGET_NTGRBAK=NtgrBak
TARGET_NVEX=NVEx
TARGETS=$(TARGET_NTGRBAK) $(TARGET_NVEX)
LIBS_NTGRBAK=-lcrypto
LIBS_NVEX=
OBJS_NTGRBAK=\
src/config.o\
src/crypt.o\
src/NtgrBak.o
OBJS_NVEX=\
src/nvram.o\
src/NVEx.o

CFLAGS_DEFAULT=-Wall
CFLAGS_DEBUG=-g3
CFLAGS_RELEASE=-g0
LDFLAGS_DEFAULT=
LDFLAGS_DEBUG=
LDFLAGS_RELEASE=-s

ifdef DEBUG
CFLAGS=$(CFLAGS_DEFAULT) $(CFLAGS_DEBUG)
LDFLAGS=$(LDFLAGS_DEFAULT) $(LDFLAGS_DEBUG)
else
CFLAGS=$(CFLAGS_DEFAULT) $(CFLAGS_RELEASE)
LDFLAGS=$(LDFLAGS_DEFAULT) $(LDFLAGS_RELEASE)
endif


all: $(TARGETS)

$(TARGET_NTGRBAK): $(OBJS_NTGRBAK)
	$(CC) $(LDFLAGS) $(LIBS_NTGRBAK) -o $(TARGET_NTGRBAK) $(OBJS_NTGRBAK)

$(TARGET_NVEX): $(OBJS_NVEX)
	$(CC) $(LDFLAGS) $(LIBS_NVEX) -o $(TARGET_NVEX) $(OBJS_NVEX)

%.o: %.c %.h
	$(CC) -c $< $(CFLAGS) $(LIBS) -o $@

clean:
	rm -vf src/*.o
	rm -vf $(TARGETS)
